### ISSUE TITLE
Try to keep styles within the CSS file

### ISSUE THREAD

**Issue by SidTheEngineer** [KhalilEtTkhyly/prj-rev-bwfs-dasmoto#2]
It is now a best practice to avoid inline styling on elements, and instead, keep them within a `.css` file. Here is an example of what I mean:

```HTML
<h3 style="background-color: mediumspringgreen;">Brushes</h3>
```

can instead be turned into an element that has a class that is addressed within a css file:

```HTML
<h3 class="spring-green">Brushes</h3>
```

```CSS
.spring-green {
  background-color: mediumspringgreen;
}
```

In this way, we avoid too much clutter within our HTML files when adding more and more styles 🙂.
